### ISSUE TITLE
Arguments to old extract_vector not working anymore in new version of pyspatialml

### ISSUE THREAD

**Issue by awa5114** [stevenpawley/Pyspatialml#18]
I have some old code which I'm pretty sure worked fine with `pyspatialml` about a year ago. However the latest version of pyspatialml seems to break it:

`train_data = stack.extract_vector(response=train_data, field='landslide')`

> TypeError: extract_vector() got an unexpected keyword argument 'response'

I dug through the git history with the following command:

`git log -L 372,+3:pyspatialml/base.py`

I found that a number of modifications were made in the `extract_vector` function, but none of them make use of either the `response` or the `field` argument. Am I missing something? How can I make sure the above code works again?

Thanks.

**Comment by awa5114** [comment]
I just looked through your tests. It seems that `extract_vector` now gets rid of all the columns in the input `geodataframe`? This causes a problem when `extract_vector` is called with a polygon geodataframe. Consider the following variation on `test_classification`:

        training_py = gpd.read_file(nc.polygons)
        df_polygons = self.stack_nc.extract_vector(gdf=training_py)

`training_py` abd `df_polygons` will have different sizes, and the `y` vector cannot be retrieved unless some pretty wild workarounds are implemented... Am I right that this is a regression from the way the code worked previously?

**Comment by stevenpawley** [comment]
Hi,

Apologies for the breaking changes. I wanted to make the behaviour consistent in respect to the inputs/outputs when extracting data, i.e. the returned dataframe is the same shape as the input. This does leave a little more work for the user to bind the existing information back into the extracted data.

The extracted data will contain an "id" column which is the GeoDataFrame index of the input data. So for polygons, the extracted data will be longer because each row represents a pixel, but the "id" is the index for each polygon. So for instance, if you have labelled polygons, then you can bind this information back onto the extracted training data using a pandas.merge based on the "id" column.
