### ISSUE TITLE
Mask missing values from evaluation matrix

### ISSUE THREAD

**Issue by Itunuadedeji** [stevenpawley/Pyspatialml#31]
Hello Stephen,

I am currently working on fitting machine learning models to spatial data where my predictors are in raster format data, and response is a point geometry (in-stream concentration). Since the point data is not available everywhere, and also the raster file comes with a lot of empty grids not included in the watershed boundary. Is there a way to mask the NA values and empty grids (-9999 values) from the machine learning evaluation matrices so that I only have an evaluation (R2, RMSE etc.) for only available observations? My professor thinks I can do this by reaching out to the package creators and modifying the source code.

**Comment by stevenpawley** [comment]
Hello, I'm not sure if I am completely understanding what you are looking to achieve, but the predict method should usually not output predictions for pixels where one or more RasterLayer's in the Raster contain missing values, i.e. a single missing value in one of the grids will cause that pixel to be omitted from the prediction, even if some of the other layers do contain values. That assumes that the nodata values are set correctly for each of the input datasets, i.e. rasterio recognizes your -9999 as a nodata value.

Is this what you mean, because currently you are getting predictions for pixels that contain -9999 pixel values that should represent nodata values?

**Comment by Itunuadedeji** [comment]
This is great information. I was under the assumption that machine learning algorithms cannot work with missing data once the stacks are coerced into a data frame or an array.  What I want specifically is to fit a machine learning model to a raster stack. My response is a rasterized point feature dataset with few observations, meaning over 90% of the cells have no data values. I want the algorithm to bypass the no data values and give evaluation only for grids with available data, then I can use the trained model to predict the other no data values. 

Also, you mentioned that a single missing value will cause the grid to be omitted. Do you mean all the aligned grids (i.e all rasters across the stack with cell I.D [2,3]) will be omitted even if a few have values, or just that single empty grid will be omitted?
 
Secondly, does the model make a distinction between the no data values that fall outside a watershed boundary from those that fall within? I plan to make predictions only for the grid cells within a delineated watershed boundary. If not, It's ok I think I can always clip the polygon boundary to the predicted surface.

On another note, is it possible to have predictors as rasters and response as point feature format?

**Comment by RichardScottOZ** [comment]
Any pixel with no data will become nodata, not the entire grid.

**Comment by Itunuadedeji** [comment]
Got you. Sorry I meant pixels/cells not entire grid.
